CREATE DATABASE libretadb

CREATE TABLE libreta(
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) UNIQUE,
  description VARCHAR(255)
);

CREATE TABLE contactos(
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(255) UNIQUE,
  numero VARCHAR(255)
);